### PR TITLE
Added "not" and "hasCompletedQuest" conditions

### PR DESCRIPTION
**Pull request by AlbertoRota**

### CODE REVIEW

**Comment by Silverfeelin** [comment]
Thanks for your contribution. The code looks good to me.

Please note that the Quickbar is a subset of [sb.StardustSuite](https://github.com/zetaPRIME/sb.StardustSuite), meaning changes made to this repository should also be made to StardustLib. This repository isn't a fork due to the amount of unrelated content in the main repository. Instead, changes related to the Quickbar are mirrored.

Here's the file in the original repository:
https://github.com/zetaPRIME/sb.StardustSuite/blob/master/StardustLib/sys/stardust/quickbar/conditions.lua
If you could apply the changes there and submit a PR I'll make sure the changes are included in the next Quickbar Mini release both on GitHub and Steam. It seems that the Quickbar is a commit behind StardustLib so I will fix this later today (#3).

**Comment by AlbertoRota** [comment]
PR created here:
https://github.com/zetaPRIME/sb.StardustSuite/pull/11

**Comment by Silverfeelin** [comment]
I went ahead and mirrored the changes from StardustLib. Could you update the PR for the new structure? I'd do it myself but don't want to take credit for copying your changes over. Sorry for the inconvenience!

**Comment by AlbertoRota** [comment]
I'm going to be away from my laptop for a few days, feel absolutely free to do the needed changes, I'm doing this because I wanted to help, not for fame, so no problem there ;)

**Pull request merged**
